Follow up I92b8637c: Fix Python 3 compatibility.
This should fix the error I get when trying to update from git-review 1.19:

alex@alex:/var/www/MediaWiki/Git/core$ sudo pip install -U git-review
[sudo] password for alex:
Downloading/unpacking git-review from http://pypi.python.org/packages/source/g/git-review/git-review-1.20.tar.gz#md5=d8446f99fd4ef2cc8090bef2c9eac294
  Downloading git-review-1.20.tar.gz
  Running setup.py egg_info for package git-review
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build/git-review/setup.py", line 25, in <module>
        exec(open("git-review").read())
      File "<string>", line 864
        except CommandFailed, e:
                            ^
    SyntaxError: invalid syntax
[...]

Change-Id: I1aa43f7bb14bbf68c3a63f2225fb91d1ad53124b